version: "3.8"

services:
  
  mongodb:
    image: mongo:6
    container_name: mongo-container
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - library-net


  book-service:
    build: ./book-service
    container_name: book-container
    ports:
      - "8081:8081"
    environment:
      - MONGO_URI=mongodb://mongodb:27017/librarydb
    networks:
      - library-net
    depends_on:
      - mongodb

      

  borrow-service:
    build: ./borrow-service
    container_name: borrow-container
    ports:
      - "8083:8083"
    environment:
      - MONGO_URI=mongodb://mongodb:27017/librarydb
    networks:
      - library-net
    depends_on:
      - mongodb
  

  frontend:
    build: ./frontend
    container_name: frontend-container
    ports:
      - "3000:80"
    networks:
      - library-net
    depends_on:
      - book-service
      - borrow-service
      - member-service

  member-service:
    build: ./member-service
    container_name: member-container
    ports:
      - "8082:8082"
    environment:
      - MONGO_URI=mongodb://mongodb:27017/librarydb
    networks:
      - library-net
    depends_on:
      - mongodb

networks:
  library-net:
    driver: bridge

volumes:
  mongo_data:

