apiVersion: apps/v1
kind: Deployment
metadata:
  name: member-service
  namespace: library-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: member-service
  template:
    metadata:
      labels:
        app: member-service
    spec:
      containers:
      - name: member-service
        image: member-service:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8082
        env:
        - name: MONGO_URI
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: MONGO_URI
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: member-service
  namespace: library-app
spec:
  selector:
    app: member-service
  ports:
  - port: 8082
    targetPort: 8082
