apiVersion: apps/v1
kind: Deployment
metadata:
  name: book-deployment
  labels:
    app: book-service

spec:
  replicas: 2

  selector: 
    matchLabels:
      app: book-service

  template:
    metadata:
      labels:
        app: book-service

    spec:
      containers:
        - name: book-container
          image: googleyy/bookservice:v1
          ports:
            - containerPorts: 8081
        