apiVersion: apps/deployment
kind: Deployment
metadata:
  name: borrow-deployment
  labels:
    app: borrow-service

spec:
  replicas: 2

  selector:
    matchLabels:
      app: borrow-service

  template:
    metadata:
      labels:
        app: borrow-service

    spec:
      containers:
        - name: borrow-container
          image: googleyy/borrowservice:v1
          ports:
            - containerPorts: 8082